import { QuotaExhausted, isAutoGeneratedChannel, type SearchQuery, type SearchVideoHit } from '@/lib/youtube/search';
import { YouTubeError } from '@/lib/youtube/client';
import type { Retriever, RunControl } from './retriever';
import { canonicalChannelId, evidenceFrom, mergeCandidates } from './candidates';
import type { Coverage, DiscoveryCandidate } from './types';
import type { DiscoveryLimits } from './limits';

/**
 * The retrieval half every mode shares: run some queries, resolve the channels,
 * and come back with candidates and an honest account of what was reached.
 *
 * VIDEOS FIRST, CHANNELS SECOND. A `type=video` search names the channel of
 * every hit in the same response, so one search call yields up to fifty
 * candidate channels; `channels.list` then enriches fifty of them for one more
 * unit. The reverse order — searching channels, then finding their videos —
 * costs a search call per channel and searches a thinner surface.
 *
 * AND THEN VIDEOS AGAIN, deliberately. The `description` in a search snippet is
 * TRUNCATED; the disclosure, the affiliate link and most of the words a
 * customer's terms would match live past the cut. Matching on a snippet finds
 * the strong cases and silently misses the rest, and "silently misses the rest"
 * is indistinguishable, on the page, from "this channel does not talk about
 * that". One `videos.list` call per fifty hits buys the full text for a unit.
 *
 * NOTHING HERE STOPS ON AN ERROR IT CAN SURVIVE. A run that has collected
 * thirty candidates and then hits the quota wall returns thirty candidates and
 * says why it stopped. Turning that into a failure — or worse, into "no
 * matching creators" — is the defect this is written against.
 */

export interface QueryPlanEntry {
  q: string;
  /** Terms to match in retrieved text, so "why it appeared" is checkable. */
  terms: string[];
  /** Kept with the query so a reason can name it. */
  why: string;
  paidOnly?: boolean;
}

export interface CollectOptions {
  plan: QueryPlanEntry[];
  base: Omit<SearchQuery, 'q' | 'pageToken' | 'videoPaidProductPlacement'>;
  limits: DiscoveryLimits;
  /** Channel ids never to return — the reference channel, and anything already saved. */
  exclude?: string[];
  control?: RunControl;
}

export interface CollectResult {
  candidates: DiscoveryCandidate[];
  /** Per channel, which query found it first. */
  foundBy: Map<string, QueryPlanEntry>;
  /** Every video actually retrieved, for citation checking. */
  retrievedVideoIds: Set<string>;
  coverage: Coverage;
}

export async function collectCandidates(
  retriever: Retriever,
  options: CollectOptions,
): Promise<CollectResult> {
  const { plan, base, limits, control } = options;
  const collectedAt = retriever.now().toISOString();
  const excluded = new Set(
    (options.exclude ?? []).map((id) => canonicalChannelId(id)).filter((id): id is string => !!id),
  );

  const hits: { hit: SearchVideoHit; entry: QueryPlanEntry }[] = [];
  const queriesRun: string[] = [];
  let pagesRead = 0;
  let stoppedBecause: Coverage['stoppedBecause'] = 'complete';

  for (const entry of plan.slice(0, limits.queries)) {
    if (!retriever.ledger.canSearch()) {
      stoppedBecause = retriever.ledger.exhausted() === 'units' ? 'quota_units' : 'quota_search_calls';
      break;
    }
    if (control && !(await control.checkpoint('searching', entry.q))) {
      stoppedBecause = 'cancelled';
      break;
    }

    try {
      const page = await retriever.searchVideos({
        ...base,
        q: entry.q,
        ...(entry.paidOnly ? { videoPaidProductPlacement: true } : {}),
      });
      queriesRun.push(entry.q || 'All topics');
      pagesRead += 1;
      for (const hit of page.items) hits.push({ hit, entry });
    } catch (error) {
      if (error instanceof QuotaExhausted) {
        stoppedBecause = error.bound === 'units' ? 'quota_units' : 'quota_search_calls';
        break;
      }
      if (error instanceof YouTubeError && error.reason === 'quotaExceeded') {
        stoppedBecause = 'quota_units';
        break;
      }
      // One query failing is not the run failing, and it is certainly not an
      // absence of creators. Record it and carry on with the others.
      stoppedBecause = 'api_error';
      continue;
    }

    if (new Set(hits.map((h) => h.hit.channelId)).size >= limits.candidates) {
      stoppedBecause = 'candidate_cap';
      break;
    }
  }

  // Order matters: this is YouTube's own ordering, flattened across queries, and
  // it is what breaks ties later. Dedupe preserves first appearance.
  const orderedChannelIds: string[] = [];
  for (const { hit } of hits) {
    const id = canonicalChannelId(hit.channelId);
    if (!id || excluded.has(id) || orderedChannelIds.includes(id)) continue;
    if (orderedChannelIds.length >= limits.candidates) {
      stoppedBecause = stoppedBecause === 'complete' ? 'candidate_cap' : stoppedBecause;
      break;
    }
    orderedChannelIds.push(id);
  }

  // Not asked again once the run is already stopping: a cancelled run that
  // checkpoints a second time bills another round trip to be told the same
  // thing, and made the cancellation look like two separate events in the log.
  if (stoppedBecause !== 'cancelled' && control && !(await control.checkpoint('enriching'))) {
    stoppedBecause = 'cancelled';
  }

  const wanted = new Set(orderedChannelIds);
  const videoIds = hits
    .filter(({ hit }) => wanted.has(hit.channelId))
    .map(({ hit }) => hit.videoId)
    .slice(0, limits.videos);

  const [channelFacts, videoFacts] = await Promise.all([
    orderedChannelIds.length ? retriever.fetchChannels(orderedChannelIds).catch(() => []) : Promise.resolve([]),
    videoIds.length ? retriever.fetchVideos(videoIds).catch(() => []) : Promise.resolve([]),
  ]);

  const factsByVideo = new Map(videoFacts.map((v) => [v.videoId, v]));
  const factsByChannel = new Map(channelFacts.map((c) => [c.channelId, c]));
  const foundBy = new Map<string, QueryPlanEntry>();

  const merged = mergeCandidates(
    orderedChannelIds.flatMap((channelId) => {
      const facts = factsByChannel.get(channelId);
      // A channel that did not come back from channels.list is not a candidate:
      // it may have been deleted between the search and the enrich, and a row
      // built from the search snippet alone would carry a title and no figures
      // while looking exactly like one that has them.
      if (!facts) return [];
      // A "- Topic" catalogue channel has uploads and statistics like any other
      // and belongs to nobody a buyer can brief.
      if (isAutoGeneratedChannel(facts.title)) return [];

      const own = hits.filter(({ hit }) => hit.channelId === channelId);
      const entry = own[0]?.entry;
      if (entry) foundBy.set(channelId, entry);

      return [
        {
          facts,
          collectedAt,
          reason: entry ? `Matched the search “${entry.q}”.` : 'Matched this search.',
          evidence: own.map(({ hit, entry: hitEntry }) =>
            evidenceFrom(hit, hitEntry.terms, factsByVideo.get(hit.videoId)),
          ),
        },
      ];
    }),
  );

  const spend = retriever.ledger.read();

  return {
    candidates: merged,
    foundBy,
    retrievedVideoIds: new Set(videoFacts.map((v) => v.videoId)),
    coverage: {
      queries: queriesRun,
      searchCalls: spend.searchCalls,
      otherCalls: spend.otherCalls,
      unitsSpent: spend.units,
      pagesRead,
      resultsSeen: hits.length,
      truncated: stoppedBecause !== 'complete' || plan.length > limits.queries,
      stoppedBecause,
      collectedAt,
    },
  };
}
