import { COMPETITOR_SUGGESTIONS, EVIDENCE_INFERENCE } from '@/lib/report/policy';
import { isAutoGeneratedChannel, QuotaExhausted } from '@/lib/youtube/search';
import { YouTubeError } from '@/lib/youtube/client';
import { canonicalChannelId, channelUrl, evidenceFrom } from './candidates';
import { brandQueries, classifyEvidence, evidenceStrength } from './evidence';
import { collaborationLimits, type DiscoveryLimits } from './limits';
import { depthSignal, rankCandidates, scoreSignals, type Signal } from './rank';
import type { Retriever, RunControl } from './retriever';
import type { CompetitorInput } from './schemas';
import type {
  CollaborationRecord,
  DiscoveryCandidate,
  DiscoveryResult,
} from './types';

/**
 * Mode 3, in two steps that must not run into each other.
 *
 * STEP A NAMES BRANDS. STEP B SEARCHES FOR THEM. The gap between them is a
 * human confirming the list, and it is not a nicety: a model asked for
 * competitors returns plausible company names with total fluency, some of which
 * do not exist, and Step B would then spend the day's search budget looking for
 * collaborations with a company nobody has heard of and report the empty result
 * as a finding about the market. `confirmedBrands` is the only input Step B
 * takes, and `runCollaborations` refuses anything unconfirmed rather than
 * quietly skipping it.
 *
 * WHAT STEP A IS ALLOWED TO USE. Configured, permitted sources only: what the
 * customer typed, and — where the derived-analysis approval is configured and a
 * model provider is available — the model's own suggestion, labelled as a
 * suggestion. There is no third source. Scraping a competitor's website for a
 * "customers also considered" strip is not a fallback, it is the thing the
 * constraint rules out, and with no source configured the honest behaviour is
 * manual entry plus a sentence saying automatic suggestions are unavailable.
 */

export interface BrandSuggestion {
  name: string;
  relation: 'direct' | 'adjacent' | 'uncertain';
  rationale: string;
  /** Where the name came from. A customer's own entry is not a suggestion. */
  source: 'customer' | 'model';
  confirmed: boolean;
}

export type SuggestBrands = (input: CompetitorInput) => Promise<BrandSuggestion[]>;

export interface BrandStepResult {
  brands: BrandSuggestion[];
  /** Why automatic suggestions did not run, when they did not. */
  suggestionsUnavailable: string | null;
}

/**
 * Step A. The customer's own names are confirmed on arrival; anything a model
 * proposes arrives unconfirmed and stays that way until somebody says so.
 */
export async function identifyBrands(
  input: CompetitorInput,
  suggest: SuggestBrands | null,
): Promise<BrandStepResult> {
  const entered: BrandSuggestion[] = input.knownCompetitors.map((name) => ({
    name,
    relation: 'direct',
    rationale: 'You entered this brand.',
    source: 'customer',
    confirmed: true,
  }));

  if (!COMPETITOR_SUGGESTIONS) {
    return {
      brands: entered,
      suggestionsUnavailable:
        'Automatic competitor suggestions are restricted until the derived-analysis approval is configured on this deployment. Entering competitors yourself works normally.',
    };
  }
  if (!suggest) {
    return {
      brands: entered,
      suggestionsUnavailable:
        'No suggestion source is configured on this deployment, so competitors have to be entered by hand. Nothing else is consulted — adfit does not read competitors’ websites.',
    };
  }

  let suggested: BrandSuggestion[] = [];
  try {
    suggested = await suggest(input);
  } catch {
    return {
      brands: entered,
      suggestionsUnavailable:
        'The suggestion step could not complete. Entering competitors yourself works normally — and an empty suggestion list is not a finding that you have no competitors.',
    };
  }

  const seen = new Set(entered.map((b) => b.name.toLowerCase()));
  for (const suggestion of suggested) {
    const key = suggestion.name.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    entered.push({ ...suggestion, source: 'model', confirmed: false });
  }

  return { brands: entered, suggestionsUnavailable: null };
}

export interface ConfirmedBrand {
  name: string;
  products: string[];
}

export interface CollaborationOutcome extends DiscoveryResult {
  /** Grouped for the panel that shows brand → creator → videos. */
  byBrand: { brand: string; records: CollaborationRecord[] }[];
}

/**
 * Step B. Public collaboration evidence for brands somebody confirmed.
 */
export async function runCollaborations(
  retriever: Retriever,
  brands: ConfirmedBrand[],
  limits: DiscoveryLimits,
  control?: RunControl,
): Promise<CollaborationOutcome> {
  const collectedAt = retriever.now().toISOString();
  const bounds = collaborationLimits();
  const usable = brands.filter((b) => b.name.trim().length > 0).slice(0, bounds.brands);

  if (usable.length === 0) {
    return {
      mode: 'competitor',
      candidates: [],
      byBrand: [],
      coverage: coverageFrom(retriever, collectedAt, [], 0, 0, 'complete'),
      appliedFilters: { api: [], post: [] },
      emptyReason: 'competitor_unconfirmed',
      notes: ['Collaboration search runs only against brands you have confirmed.'],
    };
  }

  const queriesRun: string[] = [];
  const records: CollaborationRecord[] = [];
  const candidateVideos = new Map<string, { channelId: string; videoId: string; title: string; publishedAt: string }[]>();
  let resultsSeen = 0;
  let pagesRead = 0;
  let stopped: DiscoveryResult['coverage']['stoppedBecause'] = 'complete';

  outer: for (const brand of usable) {
    for (const query of brandQueries(brand.name, brand.products).slice(0, bounds.searchesPerBrand)) {
      if (!retriever.ledger.canSearch()) {
        stopped = retriever.ledger.exhausted() === 'units' ? 'quota_units' : 'quota_search_calls';
        break outer;
      }
      if (control && !(await control.checkpoint('searching', `${brand.name}: ${query.q}`))) {
        stopped = 'cancelled';
        break outer;
      }

      let hits;
      try {
        const page = await retriever.searchVideos({
          q: query.q,
          order: 'relevance',
          maxResults: 50,
          ...(query.paidOnly ? { videoPaidProductPlacement: true } : {}),
        });
        hits = page.items;
        queriesRun.push(query.paidOnly ? `${query.q} (paid promotion only)` : query.q);
        pagesRead += 1;
      } catch (error) {
        if (error instanceof QuotaExhausted) {
          stopped = error.bound === 'units' ? 'quota_units' : 'quota_search_calls';
          break outer;
        }
        if (error instanceof YouTubeError && error.reason === 'quotaExceeded') {
          stopped = 'quota_units';
          break outer;
        }
        stopped = 'api_error';
        continue;
      }

      resultsSeen += hits.length;
      const facts = hits.length
        ? await retriever.fetchVideos(hits.slice(0, limits.videos).map((h) => h.videoId)).catch(() => [])
        : [];
      const byVideo = new Map(facts.map((f) => [f.videoId, f]));

      for (const hit of hits) {
        const fact = byVideo.get(hit.videoId);
        // Without the full description there is nothing to classify: a search
        // snippet is truncated before most disclosures appear, and reading a
        // truncated description would systematically under-report affiliate and
        // gifting evidence while looking like a completed pass.
        if (!fact) continue;

        const record = classifyEvidence({
          brand: brand.name,
          products: brand.products,
          videoId: fact.videoId,
          channelId: fact.channelId,
          title: fact.title,
          description: fact.description,
          publishedAt: fact.publishedAt,
          paidPromotion: fact.paidPromotion,
          source: `search.list q="${query.q}"${query.paidOnly ? ' videoPaidProductPlacement=true' : ''}`,
          collectedAt,
          mayInferFromText: EVIDENCE_INFERENCE,
        });
        if (!record) continue;

        records.push(record);
        const list = candidateVideos.get(fact.channelId) ?? [];
        list.push({ channelId: fact.channelId, videoId: fact.videoId, title: fact.title, publishedAt: fact.publishedAt });
        candidateVideos.set(fact.channelId, list);
      }
    }
  }

  const channelIds = [...candidateVideos.keys()]
    .map((id) => canonicalChannelId(id))
    .filter((id): id is string => !!id)
    .slice(0, limits.candidates);

  if (control && !(await control.checkpoint('enriching'))) stopped = 'cancelled';

  const channelFacts = channelIds.length
    ? await retriever.fetchChannels(channelIds).catch(() => [])
    : [];

  const candidates: DiscoveryCandidate[] = channelFacts
    .filter((facts) => !isAutoGeneratedChannel(facts.title))
    .map((facts) => {
      const own = records.filter((r) => r.channelId === facts.channelId);
      const brandsNamed = [...new Set(own.map((r) => r.brand))];
      return {
        channelId: facts.channelId,
        title: facts.title,
        handle: facts.handle,
        avatar: facts.avatar,
        url: channelUrl(facts.channelId, facts.handle),
        description: facts.description,
        subscribers: facts.subscribers,
        hiddenSubscribers: facts.hiddenSubscribers,
        videoCount: facts.videoCount,
        viewCount: facts.viewCount,
        reason: collaborationReason(own, brandsNamed),
        evidence: own.map((record) =>
          evidenceFrom(
            {
              videoId: record.videoId,
              channelId: record.channelId,
              channelTitle: facts.title,
              title: record.videoTitle,
              description: record.excerpt ?? '',
              publishedAt: record.publishedAt,
            },
            [record.brand],
          ),
        ),
        relevance: null,
        collaborations: own,
        collectedAt,
      };
    });

  const ranked = rankCandidates(candidates, (candidate) =>
    scoreSignals(collaborationSignals(candidate)),
  );

  const byBrand = usable.map((brand) => ({
    brand: brand.name,
    records: records.filter((r) => r.brand === brand.name),
  }));

  return {
    mode: 'competitor',
    candidates: ranked,
    byBrand,
    coverage: coverageFrom(retriever, collectedAt, queriesRun, pagesRead, resultsSeen, stopped),
    appliedFilters: {
      api: [
        { name: 'Brands searched', value: usable.map((b) => b.name).join(' · ') },
        { name: 'Paid-promotion filter', value: 'applied on one query per brand (videoPaidProductPlacement)' },
      ],
      post: [
        { name: 'Brand named in retrieved text', value: 'required — a search hit that never names the brand is not evidence about it' },
        { name: 'Evidence classification', value: EVIDENCE_INFERENCE ? 'full' : 'mention only (approval not configured)' },
      ],
    },
    emptyReason:
      ranked.length > 0
        ? null
        : stopped === 'quota_units' || stopped === 'quota_search_calls'
          ? 'quota_exhausted'
          : stopped === 'api_error'
            ? 'api_error'
            : 'no_collaboration_evidence',
    notes: [],
  };
}

function coverageFrom(
  retriever: Retriever,
  collectedAt: string,
  queries: string[],
  pagesRead: number,
  resultsSeen: number,
  stoppedBecause: DiscoveryResult['coverage']['stoppedBecause'],
): DiscoveryResult['coverage'] {
  const spend = retriever.ledger.read();
  return {
    queries,
    searchCalls: spend.searchCalls,
    otherCalls: spend.otherCalls,
    unitsSpent: spend.units,
    pagesRead,
    resultsSeen,
    truncated: stoppedBecause !== 'complete',
    stoppedBecause,
    collectedAt,
  };
}

export function collaborationReason(records: CollaborationRecord[], brands: string[]): string {
  if (records.length === 0) return 'No evidence retrieved for this channel.';
  const strongest = records.reduce((best, r) =>
    RANK[r.classification] > RANK[best.classification] ? r : best,
  );
  const brandList = brands.slice(0, 3).join(', ');
  const count = records.length;

  switch (strongest.classification) {
    case 'explicit_paid':
      return `${count} video${count === 1 ? '' : 's'} naming ${brandList}; the strongest is flagged by YouTube as paid promotion and discloses it in the description.`;
    case 'affiliate':
      return `${count} video${count === 1 ? '' : 's'} naming ${brandList}, at least one carrying an affiliate link. That is a referral arrangement, not a proven sponsorship.`;
    case 'gifted':
      return `${count} video${count === 1 ? '' : 's'} naming ${brandList}, at least one stating product was provided.`;
    default:
      return `${count} video${count === 1 ? '' : 's'} naming ${brandList}. Nothing retrieved establishes a commercial relationship.`;
  }
}

const RANK: Record<CollaborationRecord['classification'], number> = {
  customer_confirmed: 5,
  explicit_paid: 4,
  affiliate: 3,
  gifted: 2,
  mention: 1,
};

export function collaborationSignals(candidate: DiscoveryCandidate): Signal[] {
  return [
    {
      key: 'evidenceStrength',
      label: 'Strength of the strongest piece of evidence',
      value: evidenceStrength(candidate.collaborations),
      weight: 3,
      missingBecause: 'No collaboration evidence was retrieved for this channel.',
    },
    {
      key: 'brandBreadth',
      label: 'How many of your confirmed brands this creator appears with',
      value: breadth(candidate),
      weight: 1,
      missingBecause: 'No brand could be tied to this channel in the retrieved text.',
    },
    {
      key: 'depth',
      label: 'Retrieved videos supporting the evidence',
      value: depthSignal(candidate.collaborations.length),
      weight: 1,
      missingBecause: 'No retrieved video named a confirmed brand.',
    },
  ];
}

function breadth(candidate: DiscoveryCandidate): number | null {
  const brands = new Set(candidate.collaborations.map((r) => r.brand));
  if (brands.size === 0) return null;
  // Capped at three: appearing with three confirmed competitors is as much as
  // this signal can say, and beyond it the number is about how many brands the
  // customer typed rather than about the creator.
  return Math.min(1, brands.size / 3);
}
