import 'server-only';

import { analyseDrivers, type Driver, type DriverVideo } from '@/lib/report/drivers';
import { YouTubeError, parseDuration, ytFetch } from './client';
import { isAutoGeneratedChannel, scope, type Scoped } from './scope';

/**
 * Why one video did what it did — measured entirely inside its own channel.
 *
 * THE BASELINE IS THE WHOLE POINT. A raw view count says nothing: on the first
 * run against the Korean trending chart, the number one video was at 0.3x its
 * own channel's median. It was trending on the platform and underperforming
 * for the creator who made it. "Did well" only means anything against the
 * thing that made it.
 *
 * And that baseline keeps this inside III.E.2: the video, the median, the
 * engagement comparison — every figure comes from one content owner's videos.
 * Nothing here may take the viewer's own channel as a comparator. The page may
 * show both reads side by side; it may not compute across them. See
 * `withinOwner` in ./scope.
 */

export interface VideoExplain {
  videoId: string;
  title: string;
  channelTitle: string;
  publishedAt: string;
  views: number;
  likes: number;
  comments: number;
  durationSec: number;
  paidPlacement: boolean;
  /** This channel's own median over the sampled uploads. */
  channelMedianViews: number;
  /** Videos the median was taken over. */
  sampleSize: number;
  subscribers: number | null;
  /** Views ÷ that channel's median. 1.0 is a typical post for them. */
  multiple: number | null;
  engagementRate: number;
  channelMedianEngagement: number;
  /** Drivers measured across that channel's catalogue, not ours. */
  drivers: Driver[];
  units: number;
}

interface RawVideo {
  id: string;
  snippet: {
    title: string;
    channelId: string;
    channelTitle: string;
    publishedAt: string;
  };
  statistics: { viewCount?: string; likeCount?: string; commentCount?: string };
  contentDetails: { duration: string };
  paidProductPlacementDetails?: { hasPaidProductPlacement?: boolean };
}

function median(xs: number[]): number {
  if (xs.length === 0) return 0;
  const s = [...xs].sort((a, b) => a - b);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

const toDriverVideo = (v: RawVideo): DriverVideo => ({
  id: v.id,
  title: v.snippet.title,
  views: Number(v.statistics.viewCount ?? 0),
  likes: Number(v.statistics.likeCount ?? 0),
  comments: Number(v.statistics.commentCount ?? 0),
  publishedAt: v.snippet.publishedAt,
  durationSec: parseDuration(v.contentDetails.duration),
  paidPlacement: Boolean(v.paidProductPlacementDetails?.hasPaidProductPlacement),
});

const engagement = (v: DriverVideo) => (v.views > 0 ? (v.likes + v.comments) / v.views : 0);

/** Four reads: the video, its channel, that channel's uploads, their stats. */
export async function explainVideo(videoId: string): Promise<Scoped<VideoExplain>> {
  let units = 0;

  const one = await ytFetch<RawVideo>('videos', {
    part: 'snippet,statistics,contentDetails,paidProductPlacementDetails',
    id: videoId,
  });
  units += one.units;
  const video = one.items[0];
  if (!video) throw new YouTubeError('No video with that link', 404, 'notFound');

  if (isAutoGeneratedChannel(video.snippet.channelTitle)) {
    throw new YouTubeError(
      `${video.snippet.channelTitle} is a channel YouTube generates automatically, not a creator. ` +
        'There is no one behind it whose format decisions could be read.',
      422,
      'autoGenerated',
    );
  }

  const chan = await ytFetch<{
    contentDetails: { relatedPlaylists: { uploads: string } };
    statistics: { subscriberCount?: string; hiddenSubscriberCount?: boolean };
  }>('channels', { part: 'contentDetails,statistics', id: video.snippet.channelId });
  units += chan.units;
  const channel = chan.items[0];
  if (!channel) throw new YouTubeError('That channel is unavailable', 404, 'notFound');

  // A channel with no uploads is a legitimate state, not a failure: YouTube
  // 404s the uploads playlist rather than returning it empty, and every brand
  // new creator arrives here. Treated as an empty catalogue so the panel can
  // say "no posts yet" instead of showing them an error on day one.
  const list = await ytFetch<{ contentDetails: { videoId: string } }>('playlistItems', {
    part: 'contentDetails',
    playlistId: channel.contentDetails.relatedPlaylists.uploads,
    maxResults: 50,
  }).catch((e: unknown) => {
    if (e instanceof YouTubeError && e.status === 404) {
      return { items: [] as Array<{ contentDetails: { videoId: string } }>, units: 1 };
    }
    throw e;
  });
  units += list.units;
  const ids = list.items.map((i) => i.contentDetails.videoId);

  const peers = ids.length
    ? await ytFetch<RawVideo>('videos', {
        part: 'snippet,statistics,contentDetails,paidProductPlacementDetails',
        id: ids.join(','),
      })
    : { items: [] as RawVideo[], units: 0 };
  units += peers.units;

  const catalogue = peers.items.map(toDriverVideo);
  const subject = toDriverVideo(video);
  const medianViews = median(catalogue.map((v) => v.views));

  return scope(video.snippet.channelId, {
    videoId,
    title: subject.title,
    channelTitle: video.snippet.channelTitle,
    publishedAt: subject.publishedAt,
    views: subject.views,
    likes: subject.likes,
    comments: subject.comments,
    durationSec: subject.durationSec,
    paidPlacement: subject.paidPlacement,
    channelMedianViews: medianViews,
    sampleSize: catalogue.length,
    // Hidden counts are absent, not zero — a channel may switch the display off.
    subscribers: channel.statistics.hiddenSubscriberCount
      ? null
      : Number(channel.statistics.subscriberCount ?? 0) || null,
    multiple: medianViews > 0 ? subject.views / medianViews : null,
    engagementRate: engagement(subject),
    channelMedianEngagement: median(catalogue.map(engagement)),
    drivers: analyseDrivers(catalogue),
    units,
  });
}

export interface ChannelAnalysis {
  channelTitle: string;
  handle: string | null;
  subscribers: number | null;
  sampleSize: number;
  medianViews: number;
  /** Peak ÷ median. A high spread means a good post is a fluke, not a floor. */
  spread: number | null;
  drivers: Driver[];
  best: DriverVideo[];
  worst: DriverVideo[];
  units: number;
}

/**
 * The creator's own catalogue, for the creator.
 *
 * Same machinery as `explainVideo` and the same single-owner scope — this is
 * just the case where the owner is the person reading. It is the one analysis
 * in the product that needs no advertiser to exist, which is why it is the
 * first thing a creator should see.
 */
export async function analyseOwnChannel(handleOrId: string): Promise<Scoped<ChannelAnalysis>> {
  let units = 0;
  const byHandle = handleOrId.startsWith('@');
  const chan = await ytFetch<{
    id: string;
    snippet: { title: string; customUrl?: string };
    contentDetails: { relatedPlaylists: { uploads: string } };
    statistics: { subscriberCount?: string; hiddenSubscriberCount?: boolean };
  }>('channels', {
    part: 'snippet,contentDetails,statistics',
    ...(byHandle ? { forHandle: handleOrId } : { id: handleOrId }),
  });
  units += chan.units;

  const channel = chan.items[0];
  if (!channel) throw new YouTubeError(`No channel for ${handleOrId}`, 404, 'notFound');

  const list = await ytFetch<{ contentDetails: { videoId: string } }>('playlistItems', {
    part: 'contentDetails',
    playlistId: channel.contentDetails.relatedPlaylists.uploads,
    maxResults: 50,
  }).catch((e: unknown) => {
    // Same reasoning as above: an uploads playlist that 404s means no public
    // uploads, which is a state to render rather than an error to raise.
    if (e instanceof YouTubeError && e.status === 404) {
      return { items: [] as Array<{ contentDetails: { videoId: string } }>, units: 1 };
    }
    throw e;
  });
  units += list.units;
  const ids = list.items.map((i) => i.contentDetails.videoId);

  const peers = ids.length
    ? await ytFetch<RawVideo>('videos', {
        part: 'snippet,statistics,contentDetails,paidProductPlacementDetails',
        id: ids.join(','),
      })
    : { items: [] as RawVideo[], units: 0 };
  units += peers.units;

  const catalogue = peers.items.map(toDriverVideo);
  const views = catalogue.map((v) => v.views);
  const med = median(views);
  const ranked = [...catalogue].sort((a, b) => b.views - a.views);

  return scope(channel.id, {
    channelTitle: channel.snippet.title,
    handle: channel.snippet.customUrl ?? (byHandle ? handleOrId : null),
    subscribers: channel.statistics.hiddenSubscriberCount
      ? null
      : Number(channel.statistics.subscriberCount ?? 0) || null,
    sampleSize: catalogue.length,
    medianViews: med,
    spread: med > 0 && views.length ? Math.max(...views) / med : null,
    drivers: analyseDrivers(catalogue),
    best: ranked.slice(0, 3),
    worst: ranked.slice(-3).reverse(),
    units,
  });
}
