import 'server-only';

import { YouTubeError, ytFetch } from './client';
import { isAutoGeneratedChannel } from './scope';

/**
 * Confirm a creator's channel exists, at signup, before anything is stored.
 *
 * Onboarding is the only moment where getting this wrong is cheap to fix — the
 * creator is looking at the field they just typed. Afterwards a bad handle is
 * silent: `social_accounts` holds a name nothing resolves, Studio renders its
 * empty state forever, and no surface in the product explains it.
 *
 * Costs 1 unit. Also returns the figures the profile needs anyway, so the
 * check is not a wasted call.
 */

export interface ResolvedChannel {
  channelId: string;
  handle: string;
  title: string;
  subscribers: number | null;
  thumbnail: string | null;
}

export type ResolveResult =
  | { ok: true; channel: ResolvedChannel }
  | { ok: false; message: string };

/**
 * A channel id, as it appears in youtube.com/channel/UC… — 24 characters, and
 * the only form `forHandle` cannot look up. `youtubeHandleSchema` passes these
 * through untouched because an id cannot be turned into a handle locally; the
 * lookup is what returns the handle, and that is what gets stored.
 */
const CHANNEL_ID = /^UC[\w-]{22}$/;

export async function resolveChannel(handle: string): Promise<ResolveResult> {
  const byId = CHANNEL_ID.test(handle);
  try {
    const { items } = await ytFetch<{
      id: string;
      snippet: { title: string; customUrl?: string; thumbnails?: { default?: { url?: string } } };
      statistics: { subscriberCount?: string; hiddenSubscriberCount?: boolean };
    }>('channels', {
      part: 'snippet,statistics',
      ...(byId ? { id: handle } : { forHandle: handle }),
    });

    const channel = items[0];
    if (!channel) {
      return {
        ok: false,
        message: byId
          ? `YouTube has no channel with the id ${handle}. Copy the address from your channel page.`
          : `YouTube has no channel at ${handle}. Check the spelling — it is the @name in your channel URL.`,
      };
    }

    if (isAutoGeneratedChannel(channel.snippet.title)) {
      return {
        ok: false,
        message: `${channel.snippet.title} is a channel YouTube generates automatically rather than one you post to. Use the handle of the channel you upload from.`,
      };
    }

    return {
      ok: true,
      channel: {
        channelId: channel.id,
        // customUrl is the real @handle. Falling back to the input is right for
        // a handle lookup and wrong for an id lookup — storing `UC…` in
        // `youtube_handle` would put a channel id where the UI prints a name.
        handle: channel.snippet.customUrl ?? (byId ? `@${channel.snippet.title}` : handle),
        title: channel.snippet.title,
        // Hidden is absent, not zero — a creator may switch the count off, and
        // storing 0 would publish "0 followers" on their own media kit.
        subscribers: channel.statistics.hiddenSubscriberCount
          ? null
          : Number(channel.statistics.subscriberCount ?? 0) || null,
        thumbnail: channel.snippet.thumbnails?.default?.url ?? null,
      },
    };
  } catch (err) {
    if (err instanceof YouTubeError && err.reason === 'quotaExceeded') {
      // Never block a signup on our own quota. The handle is stored unverified
      // and Studio will report honestly when it cannot read the channel.
      return { ok: false, message: 'Could not reach YouTube just now. Try again in a moment.' };
    }
    console.error('[youtube/resolve] failed', err);
    return { ok: false, message: 'Could not check that handle. Try again in a moment.' };
  }
}
