/**
 * III.E.2, expressed as something that can fail at runtime rather than as a
 * comment somebody will delete.
 *
 *     "Do not aggregate API Data except ... channels that are under the same
 *      content owner ... The API Client must not combine API Data from the
 *      different content owners."
 *
 * Every figure this product computes from YouTube data belongs to exactly one
 * channel. A video's multiple is against ITS OWN channel's median; a driver's
 * effect is measured inside ONE catalogue. Two such figures may sit side by
 * side on a page — the reader compares them, which is not aggregation — but no
 * code path may produce a third number derived from both.
 *
 * `Scoped<T>` carries the owner with the value so that rule is checkable, and
 * `withinOwner` is the only sanctioned way to combine. It throws rather than
 * returning null: a cross-owner computation is not a data problem to degrade
 * around, it is a bug that must not reach a user.
 */

export interface Scoped<T> {
  /** The YouTube channel this value was computed entirely inside. */
  channelId: string;
  value: T;
}

export function scope<T>(channelId: string, value: T): Scoped<T> {
  if (!channelId) throw new Error('scope: a value must name the channel it came from');
  return { channelId, value };
}

/**
 * Combine two values only when they belong to the same content owner.
 *
 * The throw is the point. Someone will eventually write "this video vs the
 * creator's median" because it is the obvious thing a comparison page wants,
 * and that is precisely the combination the policy forbids. It should fail
 * loudly in development rather than ship a number nobody can defend.
 */
export function withinOwner<A, B, R>(
  a: Scoped<A>,
  b: Scoped<B>,
  combine: (a: A, b: B) => R,
): Scoped<R> {
  if (a.channelId !== b.channelId) {
    throw new Error(
      `withinOwner: refusing to combine API Data across content owners ` +
        `(${a.channelId} vs ${b.channelId}). III.E.2 permits aggregation only ` +
        `within one owner. Render the two figures separately instead.`,
    );
  }
  return { channelId: a.channelId, value: combine(a.value, b.value) };
}

/**
 * Auto-generated channels — "Topic" channels YouTube creates for music
 * catalogues, and the Movies/Shows surfaces.
 *
 * They have uploads and statistics like any channel, so every calculation here
 * runs happily over them and produces numbers about nobody. A creator pasting
 * one has not made a mistake worth an error message; they have found a thing
 * that looks like a channel and is not one, and the page should say so.
 */
export function isAutoGeneratedChannel(title: string): boolean {
  return / - Topic$/.test(title.trim()) || /^(Movies|Shows|Sports) - /.test(title.trim());
}
