import 'server-only';

import { YouTubeError, ytFetch } from './client';
import { isAutoGeneratedChannel } from './scope';
import { QuotaLedger } from './quota';
import { parseDuration } from './parse';

/**
 * The retrieval half of discovery: the official endpoints, and nothing else.
 *
 * Everything here is `search.list`, `videos.list` and `channels.list` with
 * documented parameters against a project API key. No scraping, no undocumented
 * endpoint, no third-party index, and nothing that needs a creator to have
 * approved anything — a channel is discoverable here for exactly the reason it
 * is discoverable in YouTube's own search box.
 *
 * WHAT THE API CAN FILTER AND WHAT IT CANNOT is the distinction this module
 * exists to keep honest. `SEARCH_FILTERS` is what search.list applies itself,
 * server-side, before it returns anything. `POST_FILTERS` is what we apply
 * afterwards to what came back. They behave differently in the one way that
 * matters to a customer reading a result count: an API filter narrows the
 * whole index, a post-filter narrows one bounded page of it. A subscriber
 * range applied after retrieval does NOT mean "every channel in that range" —
 * it means "the ones in that range among the however-many we read" — and the
 * results panel has to say so.
 */

export {
  SEARCH_FILTERS,
  POST_FILTERS,
  LOCALE_PARAMETER_DISCLOSURE,
  MAX_RESULTS_PER_PAGE,
} from './search-contract';

import { MAX_RESULTS_PER_PAGE } from './search-contract';

export interface SearchVideoHit {
  videoId: string;
  channelId: string;
  channelTitle: string;
  title: string;
  description: string;
  publishedAt: string;
}

export interface SearchChannelHit {
  channelId: string;
  title: string;
  description: string;
}

export interface SearchQuery {
  q: string;
  /** ISO 639-1. A search preference — see LOCALE_PARAMETER_DISCLOSURE. */
  relevanceLanguage?: string;
  /** ISO 3166-1 alpha-2. Same caveat. */
  regionCode?: string;
  order?: 'relevance' | 'date' | 'viewCount' | 'rating' | 'title' | 'videoCount';
  publishedAfter?: string;
  videoDuration?: 'short' | 'medium' | 'long';
  videoCategoryId?: string;
  /** YouTube's own paid-promotion filter. `true` restricts to flagged videos. */
  videoPaidProductPlacement?: boolean;
  maxResults?: number;
  pageToken?: string;
}

export interface SearchPage<T> {
  items: T[];
  nextPageToken: string | null;
}

/**
 * One page of video results.
 *
 * Videos first, channels resolved after, is the deliberate order for every mode
 * here. `type=channel` searches channel titles and descriptions, which is a
 * thin and often empty surface — plenty of working channels describe themselves
 * in one line or not at all. What a channel actually makes is in its videos,
 * and a video hit names its channel in the same response, so the video route
 * finds more and costs the same one call.
 */
export async function searchVideos(
  query: SearchQuery,
  ledger: QuotaLedger,
): Promise<SearchPage<SearchVideoHit>> {
  const { items, nextPageToken } = await runSearch(query, 'video', ledger);
  return {
    items: items.flatMap((item) => {
      const videoId = item.id?.videoId;
      const snippet = item.snippet;
      if (!videoId || !snippet?.channelId) return [];
      return [
        {
          videoId,
          channelId: snippet.channelId,
          channelTitle: snippet.channelTitle ?? '',
          title: decodeEntities(snippet.title ?? ''),
          description: decodeEntities(snippet.description ?? ''),
          publishedAt: snippet.publishedAt ?? '',
        },
      ];
    }),
    nextPageToken,
  };
}

/** One page of channel results. Used only where a channel-level query is the
 *  honest shape of the question — never as the sole route into a topic. */
export async function searchChannels(
  query: SearchQuery,
  ledger: QuotaLedger,
): Promise<SearchPage<SearchChannelHit>> {
  const { items, nextPageToken } = await runSearch(query, 'channel', ledger);
  return {
    items: items.flatMap((item) => {
      const channelId = item.id?.channelId ?? item.snippet?.channelId;
      if (!channelId) return [];
      return [
        {
          channelId,
          title: decodeEntities(item.snippet?.title ?? ''),
          description: decodeEntities(item.snippet?.description ?? ''),
        },
      ];
    }),
    nextPageToken,
  };
}

interface RawSearchItem {
  id?: { videoId?: string; channelId?: string };
  snippet?: {
    channelId?: string;
    channelTitle?: string;
    title?: string;
    description?: string;
    publishedAt?: string;
  };
}

async function runSearch(
  query: SearchQuery,
  type: 'video' | 'channel',
  ledger: QuotaLedger,
): Promise<{ items: RawSearchItem[]; nextPageToken: string | null }> {
  // Asked before the call, so an exhausted budget produces a partial result
  // rather than a 403 the caller has to interpret.
  if (!ledger.canSearch()) throw new QuotaExhausted(ledger.exhausted() ?? 'search_calls');

  const params: Record<string, string | number> = {
    part: 'snippet',
    type,
    maxResults: Math.min(query.maxResults ?? MAX_RESULTS_PER_PAGE, MAX_RESULTS_PER_PAGE),
    order: query.order ?? 'relevance',
    safeSearch: 'none',
  };
  if (query.q.trim()) params.q = query.q;
  if (query.relevanceLanguage) params.relevanceLanguage = query.relevanceLanguage;
  if (query.regionCode) params.regionCode = query.regionCode;
  if (query.publishedAfter) params.publishedAfter = query.publishedAfter;
  if (query.pageToken) params.pageToken = query.pageToken;
  // Video-only parameters. Sending one with type=channel is a 400, and a 400
  // still costs a call.
  if (type === 'video') {
    if (query.videoDuration) params.videoDuration = query.videoDuration;
    if (query.videoCategoryId) params.videoCategoryId = query.videoCategoryId;
    if (query.videoPaidProductPlacement) params.videoPaidProductPlacement = 'true';
  }

  ledger.recordSearch();
  const res = await ytFetch<RawSearchItem>('search', params);
  return { items: res.items, nextPageToken: res.nextPageToken ?? null };
}

export interface ChannelFacts {
  channelId: string;
  title: string;
  handle: string | null;
  avatar: string | null;
  description: string | null;
  /** Null when the creator hides the count. Never zero — see resolve.ts. */
  subscribers: number | null;
  hiddenSubscribers: boolean;
  videoCount: number | null;
  viewCount: number | null;
  country: string | null;
  publishedAt: string | null;
}

/**
 * Enrich up to 50 channels in one call.
 *
 * `channels.list` takes a comma-separated id list and charges 1 unit for the
 * batch, which is the whole reason discovery can afford to enrich every
 * candidate it retrieves: fifty channels for one unit, against one search call
 * that produced them.
 */
export async function fetchChannels(
  channelIds: string[],
  ledger: QuotaLedger,
): Promise<ChannelFacts[]> {
  const unique = [...new Set(channelIds)].filter(Boolean);
  if (unique.length === 0) return [];

  const out: ChannelFacts[] = [];
  for (let i = 0; i < unique.length; i += 50) {
    if (!ledger.canRead()) throw new QuotaExhausted('units');
    ledger.recordRead();
    const { items } = await ytFetch<{
      id: string;
      snippet?: {
        title?: string;
        customUrl?: string;
        description?: string;
        country?: string;
        publishedAt?: string;
        thumbnails?: { default?: { url?: string }; medium?: { url?: string } };
      };
      statistics?: {
        subscriberCount?: string;
        hiddenSubscriberCount?: boolean;
        videoCount?: string;
        viewCount?: string;
      };
    }>('channels', { part: 'snippet,statistics', id: unique.slice(i, i + 50).join(','), maxResults: 50 });

    for (const item of items) {
      if (!item.id || !item.snippet?.title) continue;
      const hidden = item.statistics?.hiddenSubscriberCount === true;
      out.push({
        channelId: item.id,
        title: item.snippet.title,
        handle: item.snippet.customUrl ?? null,
        avatar: item.snippet.thumbnails?.medium?.url ?? item.snippet.thumbnails?.default?.url ?? null,
        description: item.snippet.description ?? null,
        subscribers: hidden ? null : Number(item.statistics?.subscriberCount ?? '') || null,
        hiddenSubscribers: hidden,
        videoCount: Number(item.statistics?.videoCount ?? '') || null,
        viewCount: Number(item.statistics?.viewCount ?? '') || null,
        country: item.snippet.country ?? null,
        publishedAt: item.snippet.publishedAt ?? null,
      });
    }
  }
  return out;
}

export interface VideoFacts {
  videoId: string;
  channelId: string;
  title: string;
  description: string;
  publishedAt: string;
  views: number | null;
  /**
   * YouTube's own paid-product-placement flag.
   *
   * Null is NOT false: it means the field was absent from the response, which
   * happens on videos the API does not report it for. Storing false there would
   * turn "we do not know" into "there was no paid placement", and the whole
   * collaboration feature is built on that distinction.
   */
  paidPromotion: boolean | null;
  /** Length in seconds, from contentDetails on the same call. */
  seconds: number | null;
  /**
   * The audio language the UPLOADER declared, when they declared one.
   *
   * A fact about the video's own metadata, and the only language signal public
   * data offers. It is not a measurement of what language the audience speaks,
   * and nothing here may present it as one.
   */
  declaredLanguage: string | null;
}

/** Enrich up to 50 videos in one call, same economics as `fetchChannels`. */
export async function fetchVideos(
  videoIds: string[],
  ledger: QuotaLedger,
): Promise<VideoFacts[]> {
  const unique = [...new Set(videoIds)].filter(Boolean);
  if (unique.length === 0) return [];

  const out: VideoFacts[] = [];
  for (let i = 0; i < unique.length; i += 50) {
    if (!ledger.canRead()) throw new QuotaExhausted('units');
    ledger.recordRead();
    const { items } = await ytFetch<{
      id: string;
      snippet?: {
        channelId?: string;
        title?: string;
        description?: string;
        publishedAt?: string;
        defaultAudioLanguage?: string;
        defaultLanguage?: string;
      };
      statistics?: { viewCount?: string };
      contentDetails?: { duration?: string };
      paidProductPlacementDetails?: { hasPaidProductPlacement?: boolean };
    }>('videos', {
      // One call, four parts, still one unit — the cost is per call, not per
      // part, so asking for everything the comparison needs is free.
      part: 'snippet,statistics,contentDetails,paidProductPlacementDetails',
      id: unique.slice(i, i + 50).join(','),
      maxResults: 50,
    });

    for (const item of items) {
      if (!item.id || !item.snippet?.channelId) continue;
      const flag = item.paidProductPlacementDetails?.hasPaidProductPlacement;
      out.push({
        videoId: item.id,
        channelId: item.snippet.channelId,
        title: decodeEntities(item.snippet.title ?? ''),
        description: item.snippet.description ?? '',
        publishedAt: item.snippet.publishedAt ?? '',
        views: Number(item.statistics?.viewCount ?? '') || null,
        paidPromotion: flag === undefined ? null : flag,
        seconds: item.contentDetails?.duration ? parseDuration(item.contentDetails.duration) || null : null,
        declaredLanguage:
          item.snippet?.defaultAudioLanguage ?? item.snippet?.defaultLanguage ?? null,
      });
    }
  }
  return out;
}

/**
 * A channel's recent uploads, without spending a search call.
 *
 * The uploads playlist id is the channel id with the second character changed,
 * which is a documented property of the two id namespaces, and
 * `playlistItems.list` costs 1. Doing this through `search.list?channelId=`
 * would cost one of the hundred searches a day for something that is not a
 * search.
 */
export async function fetchRecentUploads(
  channelId: string,
  limit: number,
  ledger: QuotaLedger,
): Promise<string[]> {
  if (!/^UC[\w-]{22}$/.test(channelId)) return [];
  const uploads = `UU${channelId.slice(2)}`;
  const ids: string[] = [];
  let pageToken: string | undefined;

  while (ids.length < limit) {
    if (!ledger.canRead()) break;
    ledger.recordRead();
    const { items, nextPageToken } = await ytFetch<{ contentDetails?: { videoId?: string } }>(
      'playlistItems',
      {
        part: 'contentDetails',
        playlistId: uploads,
        maxResults: Math.min(50, limit - ids.length),
        ...(pageToken ? { pageToken } : {}),
      },
    ).catch((err) => {
      // A channel with no uploads playlist is a real state, not an outage.
      if (err instanceof YouTubeError && err.status === 404) return { items: [], nextPageToken: undefined };
      throw err;
    });
    for (const item of items) if (item.contentDetails?.videoId) ids.push(item.contentDetails.videoId);
    if (!nextPageToken) break;
    pageToken = nextPageToken;
  }
  return ids.slice(0, limit);
}

export class QuotaExhausted extends Error {
  constructor(readonly bound: 'units' | 'search_calls') {
    super(bound === 'search_calls' ? 'daily search-call budget reached' : 'quota units exhausted');
    this.name = 'QuotaExhausted';
  }
}

/** Search snippets arrive HTML-escaped (`&quot;`, `&#39;`). Titles are shown. */
export function decodeEntities(text: string): string {
  return text
    .replace(/&quot;/g, '"')
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)))
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

export { isAutoGeneratedChannel };
