/**
 * What the search API can filter, what it cannot, and what a locale parameter
 * actually means.
 *
 * Split out of `search.ts` because that module is `server-only` — it holds an
 * API key — and a CLIENT form needs to print the disclosure beside the language
 * and market fields. Importing it from there compiled fine in development and
 * failed the production build with "You're importing a component that needs
 * server-only", which is the correct outcome and a confusing one at the point
 * it appears. None of this is secret and none of it touches the network.
 */

/** Applied by YouTube, across the index. Names as the API spells them. */
export const SEARCH_FILTERS = [
  'q',
  'type',
  'order',
  'publishedAfter',
  'publishedBefore',
  'relevanceLanguage',
  'regionCode',
  'videoDuration',
  'videoCategoryId',
  'videoPaidProductPlacement',
  'channelId',
  'safeSearch',
] as const;

/**
 * Applied by us, to retrieved rows only.
 *
 * Each one is a FILTER over figures YouTube supplied, not a new metric derived
 * from them: keeping a row whose `subscriberCount` falls in a range is reading
 * the number, not computing one. The distinction matters because III.E.4.h(ii)
 * reaches the second and not the first.
 *
 * They also behave differently in the one way a customer notices: an API filter
 * narrows the whole index, a post-filter narrows one bounded page of it. "10k
 * to 100k subscribers" applied after retrieval does NOT mean every channel in
 * that range — it means the ones in that range among the however-many we read.
 */
export const POST_FILTERS = [
  'subscriberRange',
  'recentViewRange',
  'excludedTopics',
  'format',
  'referenceExclusion',
  'duplicateChannel',
  'autoGeneratedChannel',
] as const;

/**
 * `relevanceLanguage` and `regionCode` are SEARCH PARAMETERS.
 *
 * They tell YouTube which results to prefer. They say nothing whatever about
 * who watches the channel that comes back — that is Analytics data, it needs
 * the creator's own OAuth grant, and no public endpoint substitutes. Rendered
 * wherever a language or market input is echoed back, because "Korean" beside a
 * result reads as an audience claim unless something says it is not one.
 */
export const LOCALE_PARAMETER_DISCLOSURE =
  'Language and market are search preferences sent to YouTube, not measurements of who watches. adfit cannot see a channel’s audience.';

export const MAX_RESULTS_PER_PAGE = 50;
