/**
 * Assertions for reference analysis and content ideas.
 *
 * Both are auxiliary features that sit next to a decision, which is exactly
 * where an unearned claim does damage. These pin the two rules the spec turns
 * on: a video is judged against ITS OWN channel and never another's, and the
 * trending chart is never presented as a recommendation for a campaign nobody
 * checked it against.
 *
 *   npm run verify:reference
 */
import { scope, withinOwner, isAutoGeneratedChannel } from '@/lib/youtube/scope';
import { parseVideoId, parseDuration } from '@/lib/youtube/parse';
import { CATEGORIES, REGIONS } from '@/lib/youtube/trending';
import { readFileSync } from 'fs';

let pass = 0, fail = 0;
function check(label: string, actual: unknown, expected: unknown) {
  const a = JSON.stringify(actual), e = JSON.stringify(expected);
  if (a === e) { pass++; console.log(`  ok   ${label}`); }
  else { fail++; console.log(`  FAIL ${label}\n       got ${a}\n       want ${e}`); }
}

// ---------------------------------------------------------------------------
// One owner at a time — the rule the whole feature rests on
// ---------------------------------------------------------------------------

const referenceChannel = scope('UC_reference', { views: 2_254_236, median: 87_828 });
const candidateChannel = scope('UC_candidate', { views: 679_904, median: 679_904 });

check(
  'a video is measured against its own channel',
  Math.round(withinOwner(referenceChannel, referenceChannel, (a, b) => a.views / b.median).value * 10) / 10,
  25.7,
);

let threw = false;
try {
  withinOwner(referenceChannel, candidateChannel, (a, b) => a.views / b.views);
} catch {
  threw = true;
}
check('comparing a reference to a candidate throws', threw, true);

// The two cases the baseline exists to separate: a big channel underperforming
// and a small channel breaking out, at similar raw view counts.
const trendingButBelowPar = 3_036_040 / 9_749_575;
const genuineBreakout = 2_254_236 / 87_828;
check('raw views cannot separate them', Math.abs(3_036_040 - 2_254_236) < 900_000, true);
check('the own-channel multiple can', trendingButBelowPar < 1 && genuineBreakout > 20, true);

// ---------------------------------------------------------------------------
// The saved read is frozen, and the schema says why
// ---------------------------------------------------------------------------

const migration = readFileSync('supabase/migrations/0034_campaign_references.sql', 'utf8');
check('references carry the date they were read', migration.includes('analysed_at    timestamptz not null'), true);
check('and the baseline the multiple was against', migration.includes('channel_median_views'), true);
check('and the sample the median came from', migration.includes('sample_size'), true);
check(
  'the column comment forbids a cross-owner multiple',
  migration.includes('never another channel'),
  true,
);
check('deleting a candidate does not bin the research', migration.includes('on delete set null'), true);

// ---------------------------------------------------------------------------
// Content ideas must not read as a recommendation
// ---------------------------------------------------------------------------

const ideas = readFileSync('src/components/campaign/ContentIdeas.tsx', 'utf8');
check('scope is in the panel meta: region, category, read date', 
  ideas.includes('{region} · {category} · read ${shortDate(readAt)}'.replace('${','${')) ||
  ideas.includes('read ${shortDate(readAt)}'), true);
check(
  'it says outright it is not what the campaign should make',
  ideas.includes('not\n        what this campaign should make') || ideas.includes('not what this campaign should make'),
  true,
);
check(
  'and that nothing was checked against the brief',
  ideas.includes('has been checked against your brief'),
  true,
);
check('the relevance judgement is handed back to the buyer', ideas.includes('relevance\n        judgement is yours') || ideas.includes('judgement is yours'), true);
check('readAt is required, not optional', ideas.includes('readAt: string;'), true);
check(
  'a thin category chart is disclosed rather than padded',
  ideas.includes('Per-category charts are'),
  true,
);
check(
  'the category is never defaulted from a candidate',
  ideas.includes('never defaulted from a candidate'),
  true,
);

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

check('a watch link parses', parseVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ'), 'dQw4w9WgXcQ');
check('a Shorts link parses', parseVideoId('https://www.youtube.com/shorts/iSWFKTJ4Luo'), 'iSWFKTJ4Luo');
check('a channel link is refused', parseVideoId('https://www.youtube.com/@jooshica6178'), null);
check('an auto-generated channel is refused', isAutoGeneratedChannel('IU - Topic'), true);
check('durations with hours parse', parseDuration('PT1H2M3S'), 3723);

check('regions are a closed list', REGIONS.length >= 3, true);
check('categories are YouTube’s fourteen', CATEGORIES.length, 14);

console.log(`\n  ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
