/**
 * Assertions for the format-driver analysis and the cross-owner guard.
 *
 * A creator acts on these numbers, so a driver that is really noise costs them
 * their next video. The eyeball reading of the first real catalogue said
 * "collabs drive hits" because the top three videos all had one; the full
 * sample put it at 0.79x with p=0.91. These pin the machinery that caught it.
 *
 *   npm run verify:drivers
 */
import { MIN_ARM, analyseDrivers, type DriverVideo } from '@/lib/report/drivers';
import { isAutoGeneratedChannel, scope, withinOwner } from '@/lib/youtube/scope';
import { parseDuration, parseVideoId } from '@/lib/youtube/parse';

let pass = 0,
  fail = 0;
function check(label: string, actual: unknown, expected: unknown) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    pass++;
    console.log(`  ok   ${label}`);
  } else {
    fail++;
    console.log(`  FAIL ${label}\n       got ${a}\n       want ${e}`);
  }
}

let seq = 0;
const vid = (title: string, views: number, over = {}): DriverVideo => ({
  id: `v${seq++}`,
  title,
  views,
  likes: Math.round(views * 0.04),
  comments: Math.round(views * 0.002),
  publishedAt: '2026-05-04T00:00:00.000Z', // a Monday
  durationSec: 30,
  paidPlacement: false,
  ...over,
});

const driver = (vs: DriverVideo[], key: string) => analyseDrivers(vs).find((d) => d.key === key)!;

// ---------------------------------------------------------------------------
// The floor
// ---------------------------------------------------------------------------

const tooFew = [
  ...Array.from({ length: 3 }, () => vid('with @someone', 5_000_000)),
  ...Array.from({ length: 30 }, () => vid('solo post', 100_000)),
];
check('a thin arm reports no multiple', driver(tooFew, 'collab').ratio, null);
check('and says why', driver(tooFew, 'collab').verdict, 'not enough posts');
check(
  'even a 50x gap does not buy its way past the floor',
  driver(tooFew, 'collab').note.includes('too few'),
  true,
);
check('the floor is both arms, not the total', MIN_ARM, 8);

const noneAtAll = Array.from({ length: 20 }, () => vid('solo post', 100_000));
check('a feature with no posts says so', driver(noneAtAll, 'collab').note, 'No posts with this feature yet.');

// ---------------------------------------------------------------------------
// A real effect, and a fake one
// ---------------------------------------------------------------------------

const real = [
  ...Array.from({ length: 12 }, (_, i) => vid('with @someone', 900_000 + i * 10_000)),
  ...Array.from({ length: 12 }, (_, i) => vid('solo post', 100_000 + i * 10_000)),
];
const realD = driver(real, 'collab');
check('a clean separation is called an effect', realD.verdict, 'raises');
check('with a multiple', realD.ratio !== null && realD.ratio > 5, true);
check('and a significant p', realD.p !== null && realD.p < 0.05, true);

// Same medians, overlapping spread — the shape that fools an eyeball.
const noisy = [
  ...Array.from({ length: 12 }, (_, i) => vid('with @someone', [50, 60, 9000, 70, 55, 65, 58, 62, 57, 61, 59, 63][i] * 1000)),
  ...Array.from({ length: 12 }, (_, i) => vid('solo post', [58, 62, 57, 61, 59, 63, 56, 64, 60, 58, 62, 60][i] * 1000)),
];
const noisyD = driver(noisy, 'collab');
check('one outlier does not create an effect', noisyD.verdict === 'raises', false);
check('because ranks ignore how far the outlier is', noisyD.p !== null && noisyD.p > 0.05, true);

// A wide gap with a hopeless p must not be described as a trend.
const hopeless = [
  ...Array.from({ length: 10 }, (_, i) => vid('with @someone', [10, 900, 20, 800, 30, 700, 40, 600, 50, 500][i] * 1000)),
  ...Array.from({ length: 10 }, (_, i) => vid('solo post', [500, 50, 600, 40, 700, 30, 800, 20, 900, 10][i] * 1000)),
];
const hopelessD = driver(hopeless, 'collab');
check('a gap with p near 1 is "no effect", not "inconclusive"', hopelessD.verdict, 'no effect');
check(
  'and is never described as something more posts would settle',
  hopelessD.note.includes('settle'),
  false,
);

// ---------------------------------------------------------------------------
// Ordering — a creator reads the top of this list
// ---------------------------------------------------------------------------

const ordered = analyseDrivers(real);
check('readable effects sort above unreadable ones', ordered[0].key, 'collab');
check(
  'unreadable rows sink to the bottom',
  ordered[ordered.length - 1].verdict,
  'not enough posts',
);

// ---------------------------------------------------------------------------
// III.E.2, enforced rather than remembered
// ---------------------------------------------------------------------------

const a = scope('UC_aaa', 100);
const b = scope('UC_aaa', 50);
const other = scope('UC_bbb', 50);

check('same owner combines', withinOwner(a, b, (x, y) => x / y).value, 2);
check('the result keeps its owner', withinOwner(a, b, (x, y) => x / y).channelId, 'UC_aaa');

let threw = false;
try {
  withinOwner(a, other, (x, y) => x / y);
} catch {
  threw = true;
}
check('combining across owners throws', threw, true);

let noScope = false;
try {
  scope('', 1);
} catch {
  noScope = true;
}
check('a value must name its channel', noScope, true);

check('a Topic channel is recognised', isAutoGeneratedChannel('IU - Topic'), true);
check('and a real one is not', isAutoGeneratedChannel('Jooshica'), false);
check('nor one that merely mentions topics', isAutoGeneratedChannel('Topic Talks'), false);

// ---------------------------------------------------------------------------
// Input parsing
// ---------------------------------------------------------------------------

check('watch URL', parseVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=9'), 'dQw4w9WgXcQ');
check('shorts URL', parseVideoId('https://www.youtube.com/shorts/iSWFKTJ4Luo'), 'iSWFKTJ4Luo');
check('youtu.be', parseVideoId('https://youtu.be/dQw4w9WgXcQ?si=x'), 'dQw4w9WgXcQ');
check('bare id', parseVideoId('dQw4w9WgXcQ'), 'dQw4w9WgXcQ');
check('no scheme', parseVideoId('youtube.com/watch?v=dQw4w9WgXcQ'), 'dQw4w9WgXcQ');
check('a channel link is refused', parseVideoId('https://www.youtube.com/@jooshica6178'), null);
check('another site is refused', parseVideoId('https://vimeo.com/123456'), null);
check('a lookalike host is refused', parseVideoId('https://notyoutube.com/watch?v=dQw4w9WgXcQ'), null);
check('nonsense is refused', parseVideoId('hello'), null);

check('duration with hours', parseDuration('PT1H2M3S'), 3723);
check('duration minutes only', parseDuration('PT2M36S'), 156);
check('duration seconds only', parseDuration('PT45S'), 45);
check('an unparseable duration is zero, not NaN', parseDuration('nonsense'), 0);

console.log(`\n  ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
