import { notFound } from 'next/navigation';
import { CampaignWorkspace } from '@/components/campaign/CampaignWorkspace';
import { CampaignExport } from '@/components/campaign/CampaignExport';
import { CampaignForm } from '@/components/campaign/CampaignForm';
import { WorkspaceLayout } from '@/components/shell/WorkspaceLayout';
import { presentCandidate } from '@/lib/campaign/presentation';
import type { Candidate, Campaign } from '@/lib/data/campaigns';
import type { ChannelReportView } from '@/lib/channel/report';
import type { AnalysisJob } from '@/types';

export default function TestPage({ searchParams }: { searchParams: { count?: string; gated?: string } }) {
  if (process.env.NODE_ENV !== 'development') notFound();
  const campaign: Campaign = { id: '00000000-0000-4000-8000-000000000001', name: 'Home espresso launch', brand: 'Northbeam', brandId: null, product: 'A compact espresso grinder for home coffee lovers.', audience: 'Home baristas', objective: 'Product understanding', avoidTopics: null, useCase: null, budgetTotal: 789123, budgetCurrency: 'USD', createdAt: new Date().toISOString() };
  const views = ['Everyday Coffee', 'The Kitchen Journal', 'Coffee with Mina', 'Studio Brew', 'Weekend Rituals'].slice(0, Number(searchParams.count ?? 5)).map((title, i) => {
    const report: ChannelReportView = { channelId: `UC${String(i).padStart(22, '0')}`, title, handle: `@creator${i}`, avatar: null, description: 'Fictional UI fixture.', subscribers: 125000, fetchedAt: new Date().toISOString(), start: '2026-06-20T00:00:00Z', end: new Date().toISOString(), windowDays: 90, videos: [{ id: 'fixture1', title: 'Making espresso at home: a complete workflow', publishedAt: '2026-09-01T00:00:00Z', views: 18200, seconds: 420, format: 'long' }, { id: 'fixture2', title: 'What to look for in your first coffee grinder', publishedAt: '2026-09-05T00:00:00Z', views: 23300, seconds: 300, format: 'long' }], comments: 200, unreadable: 1, truncated: false, promotions: [], contentProfile: null, clusters: [], derivedAllowed: false, analysedAt: null };
    const candidate: Candidate = { id: `00000000-0000-4000-8000-${String(i).padStart(12, '0')}`, channelId: report.channelId, submittedAs: title, proposedFee: i === 0 ? 654321 : null, feeCurrency: 'USD', notes: i === 0 ? 'PRIVATE-NOTE-SECRET' : null, status: i === 0 ? 'shortlisted' : i === 4 ? 'hold' : 'considering', fit: i < 2 && !searchParams.gated ? { verdict: 'PRIVATE-ASSESSMENT-SECRET', relevance: 'Recent videos demonstrate home espresso equipment and brewing routines.', audienceSignal: 'Questions from commenters about equipment.', sponsorshipRead: 'No disclosed records in this sample.', brandRisk: 'No conclusion established.', suggestedAngles: ['Home espresso workflow'], beforeYouSign: ['Confirm product experience and usage rights.'], confidence: i === 0 ? 'supported' : 'insufficient', confidenceReason: i === 1 ? 'The sample is too thin.' : null } : null, fitModel: null, fitWrittenAt: new Date().toISOString(), addedAt: new Date().toISOString(), analysis: i === 2 || i === 3 ? null : { channelId: report.channelId, title, handle: report.handle, avatarUrl: null, description: report.description, subscribers: report.subscribers, outputStats: [], promotions: [], clusters: [], risks: [], sentiment: null, purchaseIntentRate: null, purchaseIntentBasis: null, intentCommentsScored: null, engagementRate: null, commentsAnalysed: 200, commentsScanned: null, dataFetchedAt: report.fetchedAt, analysedAt: null, classified: false, analysisRan: false } };
    const jobs: AnalysisJob[] = i < 2 ? [] : [{ id: `j${i}`, kind: 'collect_channel', status: i === 2 ? 'queued' : 'failed', attempts: 1, maxAttempts: 3, queuedAt: new Date().toISOString(), startedAt: null, finishedAt: null, commentsScanned: null, findings: null, lastError: 'RAW-WORKER-SECRET', progressDone: null, progressTotal: null, progressStage: null }];
    return presentCandidate(candidate, jobs, i === 2 || i === 3 ? null : report);
  });
  return <WorkspaceLayout width="wide"><p className="mb-4 text-xs text-ink-muted print:hidden">Local UI check · Fictional data</p><CampaignWorkspace campaign={campaign} candidates={views} brandName={campaign.brand} canEvaluate={!searchParams.gated} briefEditor={<CampaignForm campaign={campaign} />} /><CampaignExport campaign={campaign} candidates={views} brandName={campaign.brand} /></WorkspaceLayout>;
}
